export const prevSeasonPositions = [
  { position: 1, name: "Man City" },
  { position: 2, name: "Arsenal" },
  { position: 3, name: "Man United" },
  { position: 4, name: "Newcastle" },
  { position: 5, name: "Liverpool" },
  { position: 6, name: "Brighton" },
  { position: 7, name: "Aston Villa" },
  { position: 8, name: "Tottenham" },
  { position: 9, name: "Brentford" },
  { position: 10, name: "Fulham" },
  { position: 11, name: "Crystal Palace" },
  { position: 12, name: "Chelsea" },
  { position: 13, name: "Wolves" },
  { position: 14, name: "West Ham" },
  { position: 15, name: "Bournemouth" },
  { position: 16, name: "Nottingham" },
  { position: 17, name: "Everton" },
  { position: 18, name: "Burnley" },
  { position: 19, name: "Sheffield" },
  { position: 20, name: "Luton" },
];

export const ZSOLTI_GUESSES = [
  { position: 1, name: "Chelsea" },
  { position: 2, name: "Liverpool" },
  { position: 3, name: "Man City" },
  { position: 4, name: "Arsenal" },
  { position: 5, name: "Man United" },
  { position: 6, name: "Tottenham" },
  { position: 7, name: "West Ham" },
  { position: 8, name: "Aston Villa" },
  { position: 9, name: "Newcastle" },
  { position: 10, name: "Brighton" },
  { position: 11, name: "Burnley" },
  { position: 12, name: "Brentford" },
  { position: 13, name: "Everton" },
  { position: 14, name: "Crystal Palace" },
  { position: 15, name: "Fulham" },
  { position: 16, name: "Wolves" },
  { position: 17, name: "Luton" },
  { position: 18, name: "Sheffield" },
  { position: 19, name: "Nottingham" },
  { position: 20, name: "Bournemouth" },
];

export const MARCI_GUESSES = [
  { position: 1, name: "Man City" },
  { position: 2, name: "Liverpool" },
  { position: 3, name: "Man United" },
  { position: 4, name: "Arsenal" },
  { position: 5, name: "Chelsea" },
  { position: 6, name: "Brighton" },
  { position: 7, name: "Newcastle" },
  { position: 8, name: "Aston Villa" },
  { position: 9, name: "Tottenham" },
  { position: 10, name: "Brentford" },
  { position: 11, name: "Burnley" },
  { position: 12, name: "Bournemouth" },
  { position: 13, name: "West Ham" },
  { position: 14, name: "Nottingham" },
  { position: 15, name: "Crystal Palace" },
  { position: 16, name: "Everton" },
  { position: 17, name: "Fulham" },
  { position: 18, name: "Wolves" },
  { position: 19, name: "Luton" },
  { position: 20, name: "Sheffield" },
];
